### ISSUE TITLE
LoadError: cannot load such file -- pg-aws_rds_iam 

### ISSUE THREAD

**Issue by houdinisparks** [haines/pg-aws_rds_iam#536]
Hi there,

I am facing an error below on rails startup:

```
rails aborted!	
LoadError: cannot load such file -- /webapp/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.180.1/lib/aws-sdk-core/log/formatter	
/webapp/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.180.1/lib/aws-sdk-core.rb:53:in `require_relative'	
/webapp/vendor/bundle/ruby/3.2.0/gems/aws-sdk-core-3.180.1/lib/aws-sdk-core.rb:53:in `<main>'	
<internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'	
<internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'	
/webapp/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'	
/webapp/vendor/bundle/ruby/3.2.0/gems/aws-sdk-rds-1.189.0/lib/aws-sdk-rds.rb:12:in `<main>'	
<internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'	
<internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'	
/webapp/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'	
/webapp/vendor/bundle/ruby/3.2.0/gems/pg-aws_rds_iam-0.5.0/lib/pg/aws_rds_iam.rb:3:in `<main>'	
<internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'	
<internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'	
/webapp/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'	
/webapp/config/application.rb:21:in `<main>'	
/webapp/Rakefile:6:in `require_relative'	
/webapp/Rakefile:6:in `<main>'	
/webapp/vendor/bundle/ruby/3.2.0/gems/railties-7.0.6/lib/rails/commands/rake/rake_command.rb:20:in `block in perform'	
/webapp/vendor/bundle/ruby/3.2.0/gems/railties-7.0.6/lib/rails/commands/rake/rake_command.rb:18:in `perform'	
/webapp/vendor/bundle/ruby/3.2.0/gems/railties-7.0.6/lib/rails/command.rb:51:in `invoke'	
/webapp/vendor/bundle/ruby/3.2.0/gems/railties-7.0.6/lib/rails/commands.rb:18:in `<main>'	
<internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'	
<internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'	
/webapp/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'	
./bin/rails:4:in `<main>'	
Caused by:	
LoadError: cannot load such file -- pg-aws_rds_iam	
/webapp/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:29:in `require'	
/webapp/config/application.rb:21:in `<main>'	
/webapp/Rakefile:6:in `require_relative'	
/webapp/Rakefile:6:in `<main>'	
/webapp/vendor/bundle/ruby/3.2.0/gems/railties-7.0.6/lib/rails/commands/rake/rake_command.rb:20:in `block in perform'	
/webapp/vendor/bundle/ruby/3.2.0/gems/railties-7.0.6/lib/rails/commands/rake/rake_command.rb:18:in `perform'	
/webapp/vendor/bundle/ruby/3.2.0/gems/railties-7.0.6/lib/rails/command.rb:51:in `invoke'	
/webapp/vendor/bundle/ruby/3.2.0/gems/railties-7.0.6/lib/rails/commands.rb:18:in `<main>'	
<internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'	
<internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:37:in `require'	
/webapp/vendor/bundle/ruby/3.2.0/gems/bootsnap-1.16.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'	
./bin/rails:4:in `<main>'	
(See full trace by running task with --trace)	
+ ./bin/rails db:migrate
````

Here is my existing setup

_Gemfile_
```ruby
# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.2.1'

gem 'bootsnap', require: false
gem 'jbuilder'
gem 'json-schema', '~> 2.8'
gem 'lograge', '~> 0.12.0'
gem 'pg', '~> 1.1'
gem 'pg-aws_rds_iam', '~> 0.5.0'
gem 'puma', '~> 5.0'
gem 'rails', '~> 7.0.4'
gem 'shakapacker', '= 6.5.5'
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]

.....
```

_config/database.yml_
```yml
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch('DATABASE_USERNAME', "root") %>
  # Note: It is quoted w strings as the sensitive values might begin w
  # yaml reserved chars: !, [, causing an error when rails parse the file.
  password: '<%= ENV.fetch("DATABASE_PASSWORD", "secret") %>'
  host: <%= ENV.fetch('DATABASE_HOST', "localhost") %>
  port: <%= ENV.fetch('DATABASE_PORT', 5432) %>
  database: <%= ENV.fetch('DATABASE_NAME', "app_development") %>

development:
  <<: *default
  database: app_development

test:
  <<: *default
  database: app_test

production:
  aws_rds_iam_auth_token_generator: "default"
  <<: *default
```

Any tips? Thanks!
