### ISSUE TITLE
Multi-database setup

### ISSUE THREAD

**Issue by lucashungaro** [haines/pg-aws_rds_iam#604]
Hello there! First of all, thanks for all the hard work on this gem!

We're deploying a Rails 7 application that uses a multi-database setup. Here's a fragment of `database.yml` that configures the 3 databases:

```
production:
  database_1:
    adapter: postgresql
    encoding: unicode
    host: <%= ENV['RDS_HOSTNAME_DB1'] %>
    database: <%= ENV['RDS_DB_NAME_DB1'] %>
    port: <%= ENV['RDS_PORT_DB1']%>
    username: <%= ENV['RDS_USERNAME_DB1'] %>
    aws_rds_iam_auth_token_generator: default

  database_2:
    adapter: postgresql
    encoding: unicode
    host: <%= ENV['RDS_HOSTNAME_DB2'] %>
    database: <%= ENV['RDS_DB_NAME_DB2'] %>
    port:  <%= ENV['RDS_PORT_DB2']%>
    username: <%= ENV['RDS_USERNAME_DB2'] %>
    aws_rds_iam_auth_token_generator: default

  database_3:
    adapter: postgresql
    encoding: unicode
    host: <%= ENV['RDS_HOSTNAME_DB3'] %>
    database: <%= ENV['RDS_DB_NAME_DB3'] %>
    port: <%= ENV['RDS_PORT_DB3']%>
    username: <%= ENV['RDS_USERNAME_DB3'] %>
    aws_rds_iam_auth_token_generator: default
  ```
  
 When booting up the application, the `database_1` connection is established successfully, but for the other two we get this error:
  
 ```
  Caused by:
PG::ConnectionBad: connection to server at "10.5.0.70", port 5432 failed: FATAL:  PAM authentication failed for user "user_iam_db2"
connection to server at "10.5.0.70", port 5432 failed: FATAL:  pg_hba.conf rejects connection for host "10.0.39.60", user "user_iam_db2", database "prod_database_2", no encryption
```

Is it maybe "caching" the first generated key and then it fails for the other dbs? Or just failing to generate it multiple times?

Any help is appreciated! Meanwhile I'm reading the gem's source code for some insight.
