### ISSUE TITLE
Connection not established error

### ISSUE THREAD

**Issue by louiscb** [haines/pg-aws_rds_iam#639]
When attempting to use this Gem in a Rails project on a EKS cluster,I run across this error:

```
/usr/local/bundle/ruby/3.3.0/gems/activerecord-6.1.7.8/lib/active_record/connection_adapters/postgresql_adapter.rb:83:in \
`rescue in new_client': connection to server at "ip_address", port 5432 failed: FATAL:  PAM authentication failed for user "user_name" (ActiveRecord::ConnectionNotEstablished)
...
/usr/local/bundle/ruby/3.3.0/gems/pg-1.5.4/lib/pg/connection.rb:696:in `async_connect_or_reset': connection to server at "172.31.15.204", port 5432 failed: FATAL:  PAM authentication failed for user "user_name" (PG::ConnectionBad)
```

I followed the steps in this [article](https://docs.aws.amazon.com/eks/latest/userguide/pod-configuration.html) in order to create a service account and associated it with the deployment of the pod. I did this with the following command:

```
eksctl create iamserviceaccount --name my-service-account --namespace default --cluster my-cluster --role-name my-role \
    --attach-policy-arn arn:aws:iam::111122223333:policy/my-policy --approve
```

I also tested that the db's iam user was created correctly on the Postgres side by generating a password for the iam-user with `aws rds generate-db-auth-token` and then logging in using psql.

Perhaps one issue is that when I view the service-account that the eksctl command created there are no Tokens set, which is different from the example on the aws docs:

```
Image pull secrets:  <none>
Mountable secrets:   <none>
Tokens:              <none>
Events:              <none>
```

My `database.yml` file looks like this:

```
production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  variables:
    statement_timeout: 300s
  host: url-east-1.rds.amazonaws.com
  database: db
  username: username
  aws_rds_iam_auth_token_generator: default
  sslmode: require
```

Doing `k describe pod` provides the following lines of interest

```
  Mounts:
    /var/run/secrets/eks.amazonaws.com/serviceaccount from aws-iam-token (ro)
    /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-zwbvl (ro)
...
Volumes:
  aws-iam-token:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  86400
```
